/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
/// librerias 
import Controlador.Conexion;
import Modelo.CuerpoAgua;
import Modelo.DensidadPoblacional;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;



/**
 *
 * @author Martin
 */
public class frmDatos extends javax.swing.JFrame {

    /**
     * Creates new form frmDatos
     */
    public frmDatos() {
        initComponents();
    }
    /// metodo para limpiar despues de poner la informacion en la pestaña de "Editar/Eliminar"
    public void Limpiar(){
        txtNombre2.setText("");
        txtID2.setText("");
        txtID3.setText("");
        txtMunicipio2.setText("");
        txtTipoAgua2.setText("");
        txtTipoCuerpoAgua2.setText("");
        txtIRCA2.setText(""); 
    }
      /// metodo2 para limpiar despues de poner la informacion en la pestaña de "Ingresar"
    public void Limpiar2(){
        txtNombre.setText("");
        txtID.setText("");
        txtMunicipio.setText("");
        txtTipoAgua.setText("");
        txtTipoCuerpoAgua.setText("");
        txtIRCA.setText(""); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTipoCuerpoAgua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTipoAgua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIRCA = new javax.swing.JTextField();
        Ingresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        Procesar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtID2 = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtID3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMunicipio2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTipoCuerpoAgua2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTipoAgua2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtIRCA2 = new javax.swing.JTextField();
        Editar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtNhabitantes = new javax.swing.JTextField();
        Procesar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reto 5");

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");

        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("ID");

        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Municipio");

        txtMunicipio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Tipo De Cuerpo De Agua");

        txtTipoCuerpoAgua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Tipo De Agua");

        txtTipoAgua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("IRCA");

        txtIRCA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Ingresar.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        Ingresar.setText("Ingresar");
        Ingresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(txtTipoCuerpoAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTipoAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtIRCA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(0, 324, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoCuerpoAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIRCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addComponent(Ingresar)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingresar", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));

        txtEntrada.setColumns(20);
        txtEntrada.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtEntrada.setRows(5);
        txtEntrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(txtEntrada);

        txtSalida.setColumns(20);
        txtSalida.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtSalida.setRows(5);
        txtSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane2.setViewportView(txtSalida);

        jButton1.setText("Obtener Datos");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Procesar.setText("Procesar Datos");
        Procesar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Procesar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(Procesar)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Procesar Datos", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("ID");

        txtID2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Buscar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Resultado de Busqueda");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Nombre");

        txtNombre2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setText("ID");

        txtID3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setText("Municipio");

        txtMunicipio2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Tipo De Cuerpo De Agua");

        txtTipoCuerpoAgua2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Tipo De Agua");

        txtTipoAgua2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setText("IRCA");

        txtIRCA2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Editar.setText("Editar");
        Editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(51, 51, 51)
                                        .addComponent(txtID2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNombre2)
                                            .addComponent(jLabel9)
                                            .addComponent(txtTipoCuerpoAgua2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTipoAgua2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel13)
                                            .addComponent(txtID3))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel11)
                                    .addComponent(txtMunicipio2)
                                    .addComponent(txtIRCA2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                        .addContainerGap(297, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMunicipio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoAgua2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIRCA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoCuerpoAgua2))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Editar)
                    .addComponent(Eliminar))
                .addGap(97, 97, 97))
        );

        jTabbedPane1.addTab("Editar/Eliminar", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setText("Numero de Habitantes :");

        txtNhabitantes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Procesar2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Procesar2.setText("Procesar");
        Procesar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Procesar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Procesar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel15)
                .addGap(39, 39, 39)
                .addComponent(txtNhabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(Procesar2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNhabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Procesar2))
                .addContainerGap(290, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Afeccion", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        CuerpoAgua CA= new CuerpoAgua();

        CA.setID(Integer.parseInt(txtID2.getText()));

        /// creo la connecion
        Connection Con = Conexion.Conectar();
        String sql = "delete  from CuerpoAgua where ID=? ";
        try {
            PreparedStatement ps = Con.prepareStatement(sql);
            ps.setInt(1, CA.getID());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Cuerpo de agua esta Eliminado");
            Limpiar();
        } catch (SQLException e) {
            System.out.println(e.getMessage());

        }
        try {
            Con.close()
            ;
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
        CuerpoAgua CA= new CuerpoAgua();
        CA.setNombreCuerpoAgua(txtNombre2.getText());
        CA.setID(Integer.parseInt(txtID3.getText()));
        CA.setMuncipio(txtMunicipio2.getText());
        CA.setTipoCuerpoAgua(txtTipoCuerpoAgua2.getText());
        CA.setTipoAgua(txtTipoAgua2.getText());
        CA.setClasIRCA(Double.parseDouble(txtIRCA2.getText()));
        /// creo la connecion
        Connection Con = Conexion.Conectar();
        String sql = "update CuerpoAgua set Nombre=?,Municipio=?,TipoCuerpoAgua=?,TipoAgua=?,IRCA=? where ID=? ";
        try {
            PreparedStatement ps = Con.prepareStatement(sql);
            ps.setString(1, CA.getNombreCuerpoAgua());

            ps.setString(2, CA.getMuncipio());
            ps.setString(3, CA.getTipoCuerpoAgua());
            ps.setString(4, CA.getTipoAgua());
            ps.setDouble(5, CA.getClasIRCA());
            ps.setInt(6, CA.getID());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Cuerpo de agua esta editado");
            Limpiar();
        } catch (SQLException e) {
            System.out.println(e.getMessage());

        }
        try {
            Con.close()
            ;
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_EditarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed

        /// creo una instacia para el objecto
        CuerpoAgua Ca= new CuerpoAgua();
        /// creo la connexion
        Connection Con = Conexion.Conectar();
        String sql = "select * from CuerpoAgua where ID=? ";
        ResultSet rs;/// ESTE ES EL QUE TIENE EL RESULTADO DE LA CONSULTA
        try {
            PreparedStatement ps = Con.prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(txtID2.getText())); // pido el Dato a buscar en la base  de datos
            rs=ps.executeQuery();
            if (rs.next()) {
                /// les pido los Datos guardados del Dato que mandaron a buscar en la base de datos
                Ca.setNombreCuerpoAgua(rs.getString("Nombre"));
                Ca.setID(rs.getInt("ID"));
                Ca.setMuncipio(rs.getString("Municipio"));
                Ca.setTipoCuerpoAgua(rs.getString("TipoCuerpoAgua"));
                Ca.setTipoAgua(rs.getString("TipoAgua"));
                Ca.setClasIRCA(rs.getDouble("IRCA"));

                /// le doy los Datos a los text field de la pestaña Editar/Eliminar
                txtNombre2.setText(Ca.getNombreCuerpoAgua());
                txtID3.setText(String.valueOf(Ca.getID()));
                txtMunicipio2.setText(Ca.getMuncipio());
                txtTipoCuerpoAgua2.setText(Ca.getTipoCuerpoAgua());
                txtTipoAgua2.setText(Ca.getTipoAgua());
                txtIRCA2.setText(String.valueOf(Ca.getClasIRCA()));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        /// cierro conexion
        try {
            Con.close()
            ;
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void ProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesarActionPerformed
        // TODO add your handling code here:
        txtSalida.setText("");
        String Datos=txtEntrada.getText().strip();//tomo la informacion de datos ingresados y despues con el comando "stip" elimina los espacios
        String Vector[]= Datos.split("\n");/// Divido por linea cada datos
        /// creo vector
        CuerpoAgua VectorDatos[]= new CuerpoAgua[Vector.length];/// este vector se llena con la informacion que esta en  datos ingresados
        for (int i = 0; i < Vector.length; i++) {
            String tem[]=Vector[i].split(" ");/// creo un vector para separar los datos
            System.out.println(tem[0]);
            System.out.println(Integer.parseInt(tem[1]));
            System.out.println(tem[2]);
            System.out.println(tem[3]);
            System.out.println(tem[4]);
            System.out.println(Double.parseDouble(tem[5]));
            VectorDatos[i]= new CuerpoAgua(tem[0],Integer.parseInt(tem[1]),tem[2],tem[3],tem[4],Double.parseDouble(tem[5]));// despues lleno el vector con cada dato
            VectorDatos[i].setClasIRCA(Double.parseDouble(tem[5]));
            ///System.out.println(VectorDatos[i].getClasIRCA()+"na");
        }

        ///Indicar cuál fue el nivel de riesgo de cada cuerpo de agua.
        String nivel="";

        for (int i = 0; i < Vector.length; i++) {
            nivel = VectorDatos[i].nivelIRCA();
            System.out.println(nivel);
            txtSalida.setText(txtSalida.getText()+nivel+"\n");

        }

        /// Indicar cuántos cuerpos de agua tienen un nivel de riesgo MEDIO o inferior.
        System.out.printf("%.2f \n" ,CuerpoAgua.getContador());
        txtSalida.setText(txtSalida.getText()+CuerpoAgua.getContador()+"\n");

        /*Indicar el Nombre de los cuerpos de agua que tienen un nivel de riesgo MEDIO,
        en caso de no haber ninguno devolver NA.
        */
        int cdm=0;
        String nombreMedio="";
        for (int i = 0; i < VectorDatos.length; i++) {

            if (VectorDatos[i].getClasIRCA()<=35 && VectorDatos[i].getClasIRCA()>14) {
                System.out.print(VectorDatos[i].getNombreCuerpoAgua()+"\n");
                nombreMedio = nombreMedio.strip()+"\n"+VectorDatos[i].getNombreCuerpoAgua();
                cdm++;

            }
        }
        if (cdm==0) {
            System.out.print("NA \n");
            txtSalida.setText(txtSalida.getText()+"NA"+"\n");

        }
        else {
            txtSalida.setText(txtSalida.getText()+nombreMedio+"\n");
        }

        ///Indicar el nombre del cuerpo de agua con la clasificación IRCA más baja encontrada y
        ///su número identificador.
        Double menor=999999999.0;
        int id=0;
        String Nombre="";
        for (int i = 0; i <VectorDatos.length ; i++) {
            if (VectorDatos[i].getClasIRCA()< menor) {
                menor=VectorDatos[i].getClasIRCA();
                id=VectorDatos[i].getID();
                Nombre=VectorDatos[i].getNombreCuerpoAgua();
            }
        }
        txtSalida.setText(txtSalida.getText()+Nombre+" "+id);
    }//GEN-LAST:event_ProcesarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ///traigo los Datos de la base de datos hacia un ArrayList VECTOR
        ArrayList<CuerpoAgua> Vector = new  ArrayList<>();/// Escrutura  del ArrayList =  ArrayList<> nombrte_del_vector = new ArrayList<>();
        ResultSet rs;
        String sql="select * from CuerpoAgua";
        Connection Con = Conexion.Conectar();
        try {
            PreparedStatement ps = Con.prepareStatement(sql);
            rs=ps.executeQuery();
            while(rs.next()){
                CuerpoAgua cA = new CuerpoAgua();
                cA.setNombreCuerpoAgua(rs.getString("Nombre"));
                cA.setID(rs.getInt("ID"));
                cA.setMuncipio(rs.getString("Municipio"));
                cA.setTipoCuerpoAgua(rs.getString("TipoCuerpoAgua"));
                cA.setTipoAgua(rs.getString("TipoAgua"));
                cA.setClasIRCA(rs.getDouble("IRCA"));
                Vector.add(cA);

            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        try {
            Con.close()
            ;
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        for (CuerpoAgua cuerpoAgua : Vector) {

            txtEntrada.setText(txtEntrada.getText()+cuerpoAgua.getNombreCuerpoAgua()+" "+cuerpoAgua.getID()+" "+cuerpoAgua.getMuncipio()+" "+cuerpoAgua.getTipoCuerpoAgua()+" "+cuerpoAgua.getTipoAgua()+" "+cuerpoAgua.getClasIRCA()+"\n");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        // TODO add your handling code here:
        CuerpoAgua CA= new CuerpoAgua();    /// creo la instacia del objecto Cuerpo de Agua
        /// pidos todos los datos ingresados en la pestaña Ingresar y los guardo en el objecto
        CA.setNombreCuerpoAgua(txtNombre.getText());
        CA.setID(Integer.parseInt(txtID.getText()));
        CA.setMuncipio(txtMunicipio.getText());
        CA.setTipoCuerpoAgua(txtTipoCuerpoAgua.getText());
        CA.setTipoAgua(txtTipoAgua.getText());
        CA.setClasIRCA(Double.parseDouble(txtIRCA.getText()));
        /// creo la connecion
        Connection Con = Conexion.Conectar();
        String sql = "insert into CuerpoAgua (Nombre,ID,Municipio,TipoCuerpoAgua,TipoAgua,IRCA) values  (?,?,?,?,?,?)";

        /// mando los datos ya guardados en el objecto(CA) hacia la base de Datos sql
        try {
            PreparedStatement ps = Con.prepareStatement(sql);
            ps.setString(1, CA.getNombreCuerpoAgua());
            ps.setInt(2, CA.getID());
            ps.setString(3, CA.getMuncipio());
            ps.setString(4, CA.getTipoCuerpoAgua());
            ps.setString(5, CA.getTipoAgua());
            ps.setDouble(6, CA.getClasIRCA());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Cuerpo de agua Guardado");
            Limpiar2();
        } catch (SQLException e) {
            System.out.println(e.getMessage());

        }
        /// cierro la connexion
        try {
            Con.close()
            ;
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_IngresarActionPerformed

    private void Procesar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Procesar2ActionPerformed
        // TODO add your handling code here:
        DensidadPoblacional Habi = new DensidadPoblacional();   /// creo una instancia
        Habi.setNhabitantes(Integer.parseInt(txtNhabitantes.getText()));
        /// llamo al metodo
        int A=Habi.Afeccion();
        JOptionPane.showMessageDialog(this,A);
    }//GEN-LAST:event_Procesar2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Ingresar;
    private javax.swing.JButton Procesar;
    private javax.swing.JButton Procesar2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtEntrada;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID2;
    private javax.swing.JTextField txtID3;
    private javax.swing.JTextField txtIRCA;
    private javax.swing.JTextField txtIRCA2;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtMunicipio2;
    private javax.swing.JTextField txtNhabitantes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextArea txtSalida;
    private javax.swing.JTextField txtTipoAgua;
    private javax.swing.JTextField txtTipoAgua2;
    private javax.swing.JTextField txtTipoCuerpoAgua;
    private javax.swing.JTextField txtTipoCuerpoAgua2;
    // End of variables declaration//GEN-END:variables
}
